spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    user: sa
    password:
springdoc:
  api-docs:
    path: /api-docs