spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    user: sa
    password:
  data:
    rest:
      base-path: /api
